{"name": "Проверка авторизации несуществующим пользователем", "status": "passed", "description": "Проверяем, что ошибка авторизации возвращается корректно", "steps": [{"name": "Авторизуемся", "status": "passed", "start": 1724573813000, "stop": 1724573813240}], "start": 1724573813000, "stop": 1724573813241, "uuid": "e11b8be7-f4f4-4862-bc57-0fbe4df92e38", "historyId": "687dfdd5184ec6f54e261d4f329504ec", "testCaseId": "687dfdd5184ec6f54e261d4f329504ec", "fullName": "tests.test_login.TestLogin#test_login_incorrect_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-3239M22"}, {"name": "thread", "value": "12540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}